CXX = x86_64-w64-mingw32-g++
CXXFLAGS = -static -Isrc -Wall -Wextra -O3 -std=c++17 -Wno-unused-parameter

OUT_DIR    = bin
CXX_SRC    = src/helper.cpp
CXX_OUT    = $(OUT_DIR)/buildit

LIB_SRC    = src/buildit.cpp
LIB_HEADER = src/buildit.h

.PHONY: test
test: $(CXX_OUT)
	WINEDEBUG=fixme-all wine $(CXX_OUT) -t c test

$(CXX_OUT): $(LIB_SRC) $(LIB_HEADER) $(CXX_SRC) $(OUT_DIR)
	$(CXX) $(CXXFLAGS) $(CXX_SRC) $(LIB_SRC) -o $(CXX_OUT)

$(OUT_DIR):
	mkdir $(OUT_DIR) || echo directory bin created
